apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: 5.34.0
      sourceRef:
        kind: HelmRepository
        name: loki
      interval: 1m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
  values:
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      storage:
        type: 'filesystem'
      compactor:
        retention_enabled: true
      limits_config:
        retention_period: 60d
    monitoring:
      serviceMonitor:
        enabled: true
    singleBinary:
      replicas: 1
      persistence:
        enabled: true
        size: 25Gi
