apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: 6.4.2
      sourceRef:
        kind: HelmRepository
        name: loki
      interval: 1m
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
  values:
    deploymentMode: SingleBinary
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      storage:
        type: 'filesystem'
      compactor:
        retention_enabled: true
        delete_request_store: filesystem
      limits_config:
        retention_period: 60d
    singleBinary:
      replicas: 1
      persistence:
        enabled: true
        size: 25Gi
    read:
      replicas: 0
    write:
      replicas: 0
    backend:
      replicas: 0
