apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: loki-stack
      version: 2.8.2
      sourceRef:
        kind: HelmRepository
        name: loki
      interval: 1m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    loki:
      enabled: true
      isDefault: false
      persistence:
        enabled: true
        size: 25Gi
      config:
        # Retention period: 63 days because retention period has to be a multiple of periodic table duration which is 168h by default
        chunk_store_config:
          # To avoid querying of data beyond the retention period, max_look_back_period config in chunk_store_config must be set to a value less than or equal to what is set in table_manager.retention_period.
          max_look_back_period: 1512h
        table_manager:
          retention_deletes_enabled: true
          retention_period: 1512h
      serviceMonitor:
        enabled: true
