---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  interval: 10m0s
  chart:
    spec:
      version: "1.17.0"
      chart: base
      sourceRef:
        kind: HelmRepository
        name: istio
      interval: 1m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  dependsOn:
    - name: istio-base
  interval: 10m0s
  chart:
    spec:
      version: "1.17.0"
      chart: istiod
      sourceRef:
        kind: HelmRepository
        name: istio
      interval: 1m
#  values:
#    global:
#      istioNamespace: istio-system
#      proxy:
#        resources:
#          requests:
#            cpu: 10m
#            memory: 16Mi
#    pilot:
#      autoscaleEnabled: false
#      resources:
#        requests:
#          cpu: 100m
#          memory: 128Mi
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-gateway
  namespace: istio-system
spec:
  dependsOn:
    - name: istio-base
    - name: istiod
  interval: 10m0s
  chart:
    spec:
      version: "1.17.0"
      chart: gateway
      sourceRef:
        kind: HelmRepository
        name: istio
#  values:
#    autoscaling:
#      enabled: false
#    resources:
#      requests:
#        cpu: 10m
#        memory: 128Mi
#    service:
#      type: "${service:=LoadBalancer}"

#  values:
#    controlPlane:
#      install: true
#      spec:
#        ############################################################################
#        # Global
#        ############################################################################
#        hub: gcr.io/istio-release
#        meshConfig:
#          defaultConfig:
#            tracing:
#              sampling: 0.0
#          outboundTrafficPolicy:
#            mode: REGISTRY_ONLY
#
#        components:
#          base:
#            enabled: true
#          cni:
#            enabled: false
#          istiodRemote:
#            enabled: false
#
#          ############################################################################
#          # Pilot
#          # is responsible for the lifecycle of Envoy instances deployed
#          ############################################################################
#          pilot:
#            enabled: true
#            spec:
#              policy:
#                enabled: true
#            k8s:
#              resources:
#                requests:
#                  cpu: 100m
#                  memory: 500Mi
#              hpaSpec:
#                minReplicas: 2
#
#          ############################################################################
#          # IngressGateways
#          ############################################################################
#          ingressGateways:
#            - name: istio-ingressgateway
#              enabled: true
#              k8s:
#                resources:
#                  requests:
#                    cpu: 250m
#                    memory: 500Mi
#                hpaSpec:
#                  minReplicas: 2
#                  maxReplicas: 5
#                podAnnotations:
#                  cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
#                service:
#                  type: ClusterIP
#                serviceAnnotations:
#                  cloud.google.com/backend-config: '{"default": "backend-config"}'
#                  cloud.google.com/neg: '{"ingress": true}'
#
#          ############################################################################
#          # EgressGateways
#          ############################################################################
#          egressGateways:
#            - name: istio-egressgateway
#              enabled: true
#              k8s:
#                resources:
#                  requests:
#                    cpu: 250m
#                    memory: 500Mi
#                hpaSpec:
#                  minReplicas: 2
#                  maxReplicas: 5
#                podAnnotations:
#                  cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
