---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: istio
  namespace: istio-system
spec:
  interval: 1h0m0s
  url: https://github.com/istio/istio
  ref:
    tag: 1.17.0
