---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: istio
  namespace: istio-system
spec:
  interval: 1h0m0s
  url: https://istio-release.storage.googleapis.com/charts
