---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: stevehipwell
  namespace: istio-system
spec:
  interval: 1h0m0s
  url: https://stevehipwell.github.io/helm-charts/
