apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: promtail
      version: 6.16.3
      sourceRef:
        kind: HelmRepository
        name: loki
      interval: 1m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
