apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: emissary-ingress
  namespace: ingress
spec:
  interval: 10m0s
  releaseName: emissary-ingress
  chart:
    spec:
      chart: emissary-ingress
      version: 8.4.0
      sourceRef:
        kind: HelmRepository
        name: emissary-ingress
      interval: 1m
  postRenderers:
    - kustomize:
        patchesStrategicMerge:
          - kind: Deployment
            apiVersion: apps/v1
            metadata:
              name: emissary-ingress
              namespace: ingress
            spec:
              template:
                metadata:
                  annotations:
                    cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
          - kind: Deployment
            apiVersion: apps/v1
            metadata:
              name: emissary-ingress-agent
              namespace: ingress
            spec:
              template:
                metadata:
                  annotations:
                    cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
---
