apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: emissary-ingress
  namespace: ingress
spec:
  interval: 10m0s
  releaseName: emissary-ingress
  chart:
    spec:
      chart: emissary-ingress
      version: 8.8.2
      sourceRef:
        kind: HelmRepository
        name: emissary-ingress
      interval: 1m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    agent:
      enabled: false
    podAnnotations:
      cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
---
