---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
resources:
  - ../base
#  - releases.yaml
patches:
  - target:
      kind: Deployment
      name: istio-ingressgateway
      namespace: istio-system
    patch: |-
      - op: add
        path: /spec/values/service
        value:
          annotations:
            cloud.google.com/backend-config: '{"default": "backend-config"}'
            cloud.google.com/neg: '{"ingress": true}'
