---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
resources:
  - ../base
patches:
  - target:
      kind: HelmRelease
      name: istio-ingressgateway
      namespace: istio-system
    patch: |-
      - op: add
        path: /spec/values/service/annotations
        value:
          cloud.google.com/backend-config: '{"default": "backend-config"}'
          cloud.google.com/neg: '{"ingress": true}'
