apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keda
  namespace: keda
spec:
  interval: 5m
  chart:
    spec:
      chart: keda
      version: 2.15.0
      sourceRef:
        kind: HelmRepository
        name: keda
      interval: 1m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
