---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  interval: 5m
  chart:
    spec:
      chart: kyverno
      version: v2.6.5
      sourceRef:
        kind: HelmRepository
        name: kyverno
      interval: 1m
  install:
    crds: Create
    remediation:
      retries: 10
  upgrade:
    crds: CreateReplace
