---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  interval: 10m0s
  chart:
    spec:
      chart: kyverno
      version: 3.2.7
      sourceRef:
        kind: HelmRepository
        name: kyverno
      interval: 1m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
