---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  interval: 10m
  install:
    crds: Create
    remediation:
      retries: 10
  chart:
    spec:
      chart: kyverno
      version: v3.0.0
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: kyverno
  upgrade:
    crds: CreateReplace
  values:
    # to minimize dependencies for the baseline the serviceMonitor is optional
    serviceMonitor:
      enabled: false
      namespace: monitoring
