apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd
  namespace: linkerd
spec:
  interval: 10m0s
  releaseName: linkerd
  chart:
    spec:
      chart: linkerd2
      version: 2.11.3
      sourceRef:
        kind: HelmRepository
        name: linkerd
      interval: 1m
  postRenderers:
    - kustomize:
        patchesStrategicMerge:
          - kind: Deployment
            apiVersion: apps/v1
            metadata:
              name: linkerd-destination
              namespace: linkerd
            spec:
              template:
                metadata:
                  annotations:
                    cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
          - kind: Deployment
            apiVersion: apps/v1
            metadata:
              name: linkerd-identity
              namespace: linkerd
            spec:
              template:
                metadata:
                  annotations:
                    cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
          - kind: Deployment
            apiVersion: apps/v1
            metadata:
              name: linkerd-proxy-injector
              namespace: linkerd
            spec:
              template:
                metadata:
                  annotations:
                    cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
  valuesFrom:
    - kind: Secret
      name: linkerd-trust-anchor
      valuesKey: tls.crt
      targetPath: identityTrustAnchorsPEM
    - kind: Secret
      name: webhook-issuer-tls
      valuesKey: tls.crt
      targetPath: proxyInjector.caBundle
    - kind: Secret
      name: webhook-issuer-tls
      valuesKey: tls.crt
      targetPath: profileValidator.caBundle
    - kind: Secret
      name: webhook-issuer-tls
      valuesKey: tls.crt
      targetPath: policyValidator.caBundle
  values:
    installNamespace: false
    identity:
      issuer:
        scheme: kubernetes.io/tls
    proxyInjector:
      externalSecret: true
    profileValidator:
      externalSecret: true
    policyValidator:
      externalSecret: true
---
