apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-crds
  namespace: linkerd
spec:
  interval: 10m0s
  releaseName: linkerd-crds
  chart:
    spec:
      chart: linkerd-crds
      version: 1.8.0
      sourceRef:
        kind: HelmRepository
        name: linkerd
      interval: 1m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd
  namespace: linkerd
spec:
  interval: 10m0s
  releaseName: linkerd
  chart:
    spec:
      chart: linkerd-control-plane
      version: 1.16.7
      sourceRef:
        kind: HelmRepository
        name: linkerd
      interval: 1m
  dependsOn:
    - name: linkerd-crds
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: linkerd-destination
              namespace: linkerd
            patch: |-
              kind: Deployment
              apiVersion: apps/v1
              metadata:
                name: linkerd-destination
                namespace: linkerd
              spec:
                template:
                  metadata:
                    annotations:
                      cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
          - target:
              kind: Deployment
              name: linkerd-identity
              namespace: linkerd
            patch: |-
              kind: Deployment
              apiVersion: apps/v1
              metadata:
                name: linkerd-identity
                namespace: linkerd
              spec:
                template:
                  metadata:
                    annotations:
                      cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
          - target:
              kind: Deployment
              name: linkerd-proxy-injector
              namespace: linkerd
            patch: |-
              kind: Deployment
              apiVersion: apps/v1
              metadata:
                name: linkerd-proxy-injector
                namespace: linkerd
              spec:
                template:
                  metadata:
                    annotations:
                      cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
  valuesFrom:
    - kind: Secret
      name: linkerd-trust-anchor
      valuesKey: tls.crt
      targetPath: identityTrustAnchorsPEM
    - kind: Secret
      name: webhook-issuer-tls
      valuesKey: tls.crt
      targetPath: proxyInjector.caBundle
    - kind: Secret
      name: webhook-issuer-tls
      valuesKey: tls.crt
      targetPath: profileValidator.caBundle
    - kind: Secret
      name: webhook-issuer-tls
      valuesKey: tls.crt
      targetPath: policyValidator.caBundle
  values:
    identity:
      issuer:
        scheme: kubernetes.io/tls
    proxyInjector:
      externalSecret: true
    profileValidator:
      externalSecret: true
    policyValidator:
      externalSecret: true
---
