apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  values:
    # Kubernetes switched from kube-dns to core-dns in 1.13, but GKE Kubernetes still defaults to kube-dns.
    # See https://cloud.google.com/kubernetes-engine/docs/release-notes
    coreDns:
      enabled: false
    kubeDns:
      enabled: true
---
