apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: contour
spec:
  interval: 10m0s
  releaseName: contour
  chart:
    spec:
      chart: contour
      version: 8.0.2
      sourceRef:
        kind: HelmRepository
        name: contour
      interval: 1m
---
