apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: contour
  namespace: ingress
spec:
  interval: 10m0s
  releaseName: contour
  chart:
    spec:
      chart: contour
      version: 8.0.2
      sourceRef:
        kind: HelmRepository
        name: contour
      interval: 1m
  postRenderers:
    - kustomize:
        patches:
          - patch: |-
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: not-used
              spec:
                template:
                  metadata:
                    annotations:
                      linkerd.io/inject: enabled
            target:
              kind: Deployment
              namespace: ingress
          - patch: |-
              apiVersion: apps/v1
              kind: DaemonSet
              metadata:
                name: not-used
              spec:
                template:
                  metadata:
                    annotations:
                      linkerd.io/inject: enabled
            target:
              kind: DaemonSet
              namespace: ingress
---
