apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 51.1.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      interval: 1m
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: kube-prometheus-stack-kube-state-metrics
              namespace: monitoring
            patch: |-
              kind: Deployment
              apiVersion: apps/v1
              metadata:
                name: kube-prometheus-stack-kube-state-metrics
                namespace: monitoring
              spec:
                template:
                  metadata:
                    annotations:
                      cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
          - target:
              kind: Deployment
              name: kube-prometheus-stack-grafana
              namespace: monitoring
            patch: |-
              kind: Deployment
              apiVersion: apps/v1
              metadata:
                name: kube-prometheus-stack-grafana
                namespace: monitoring
              spec:
                template:
                  metadata:
                    annotations:
                      cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
          - target:
              kind: Deployment
              name: kube-prometheus-stack-operator
              namespace: monitoring
            patch: |-
              kind: Deployment
              apiVersion: apps/v1
              metadata:
                name: kube-prometheus-stack-operator
                namespace: monitoring
              spec:
                template:
                  metadata:
                    annotations:
                      cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    coreDns:
      enabled: true
    kubeDns:
      enabled: false
    kubeControllerManager:
      enabled: false
    kubeScheduler:
      enabled: false
    alertmanager:
      alertmanagerSpec:
        podMetadata:
          annotations:
            "cluster-autoscaler.kubernetes.io/safe-to-evict": "true"
    prometheusOperator:
      admissionWebhooks:
        patch:
          podAnnotations:
            linkerd.io/inject: disabled
    prometheus:
      prometheusSpec:
        ## If true, a nil or {} value for prometheus.prometheusSpec.serviceMonitorSelector will cause the
        ## prometheus resource to be created with selectors based on values in the helm deployment
        serviceMonitorSelectorNilUsesHelmValues: false
        # CPUThrottlingHigh
        # https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/108
        # https://github.com/helm/charts/issues/14801
        additionalAlertRelabelConfigs:
          - source_labels: [ alertname ]
            regex: (CPUThrottlingHigh)
            target_label: suppress
            replacement: true
        retention: 30d
        scrapeInterval: 30s
        resources:
          limits:
            cpu: 2
            memory: 3Gi
          requests:
            cpu: 1
            memory: 2Gi
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes: [ "ReadWriteOnce" ]
              resources:
                requests:
                  storage: 100Gi
---
