---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: v4.4.2
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress-nginx
  values:
    controller:
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          namespace: ingress-nginx
          additionalLabels:
            release: prometheus-operator
      ingressClassResource:
        enabled: true
      podAnnotations:
        prometheus.io/scrape: true
        prometheus.io/port: 10254
        # optional for linkerd-stack
        linkerd.io/inject: enabled