---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 10m0s
  chart:
    spec:
      chart: ingress-nginx
      version: 4.5.2
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      interval: 1m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
