apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 10m0s
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      version: v1.14.5
      sourceRef:
        kind: HelmRepository
        name: cert-manager
      interval: 1m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    installCRDs: true
