apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  interval: 10m0s
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      version: v1.8.1
      sourceRef:
        kind: HelmRepository
        name: jetstack
      interval: 1m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    installCRDs: true
