name: lint

on:
  workflow_dispatch:
  pull_request:
    branches: [ '*' ]
    tags-ignore: [ '*' ]

permissions: read-all

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - name: Lint
        run: ./scripts/checkov.sh
