name: release

on:
  workflow_dispatch:
    branches: [ main ]
    inputs:
      version:
        description: "version to be released"
        required: true

permissions:
  contents: read
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: "0"

      - name: Release
        env:
          MR_GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          curl -L https://github.com/kharf/monoreleaser/releases/download/v0.0.3/monoreleaser-linux-amd64 --output monoreleaser
          chmod +x monoreleaser
          ./monoreleaser release . ${{ inputs.version }}


